apiVersion: v1
kind: Service
metadata:
  name: {{ template "testapi.fullname" . }}
  labels:
    app: {{ template "testapi.name" . }}
    chart: {{ template "testapi.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name:  {{ .Values.service.name }}
  selector:
    app: {{ template "testapi.name" . }}
    release: {{ .Release.Name }}